-- 000013: Rollback seed 100+ jenis surat

DELETE FROM jenis_surat WHERE kode IN (
  'SKD', 'SKP_IN', 'SKP_OUT', 'SK_DATANG', 'SK_NO_KTP', 'SK_NO_KK', 'SK_BEDANAMA', 'SK_BEDATGL',
  'SK_LAHIR', 'SK_MATI', 'SK_WARIS',
  'SP_NIKAH', 'SK_BELUM_NIKAH', 'SK_JANDA_DUDA',
  'SKTM', 'SK_PENGHASILAN',
  'SK_MILIK_TANAH', 'SK_BEBAS_SENGKETA',
  'SKU', 'SK_PETANI', 'SK_PETERNAK',
  'SKTM_SEKOLAH',
  'SP_SKCK', 'SK_KEHILANGAN',
  'SK_TERNAK_JUAL',
  'SURAT_TUGAS'
);
